name = "Orange Cake"
image = "default.png"
thc = 20
cbd = 1
profiles = ["top_crop", "azteka"]

[germination]
min = 1
max = 7
best = 3

[seedling]
min = 14
max = 21
best = 17

[vegetative]
min = 14
max = 56
best = 28

[transition]
min = 7
max = 14
best = 10

[flowering]
min = 63
max = 70
best = 65